name: Development Cycle

on:
  push:
    branches:
      - 'feature/**'
      - 'refactor/**'
      - 'bugfix/**'
      - 'proposal/**'
      - 'develop'

env:
  SOLUTION: "./WPF.sln"
  CODE_COVERAGE_COBERTURA_FILE_PATH: "./code-coverage/**/coverage.cobertura.xml"
  CODE_COVERAGE_REPORT_FOLDER_PATH: "./code-coverage/report"
  CODE_COVERAGE_FOLDER_PATH: "./code-coverage"

jobs:
  development:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ["10.0.x"]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Code Coverage Report Tool
        run: >-
          dotnet tool install -g dotnet-reportgenerator-globaltool
          --add-source ${{ vars.PACKAGE_SOURCE_URL_NUGET_ORG }}
          --version 5.5.1

      - name: Checkout Source Code
        uses: actions/checkout@v6.0.1

      - name: Register GitHub Package Registry As NuGet Source
        run: >-
          dotnet nuget add source
          --username ${{ github.repository_owner }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
          --name github ${{ vars.PACKAGE_SOURCE_URL_GITHUB }}

      - name: Run Tests
        run: >-
          dotnet test ${{ env.SOLUTION }}
          --configuration Debug
          --collect:"XPlat Code Coverage"
          --filter "Category!=RunsOnDevMachine"
          --logger:"Html;LogFileName=code-coverage-log.html"
          --nologo
          --results-directory ${{ env.CODE_COVERAGE_FOLDER_PATH }}
          --settings .runsettings
          --verbosity minimal

      - name: Generate Coverage Report
        run: >-
          reportgenerator
          "-reports:${{ env.CODE_COVERAGE_COBERTURA_FILE_PATH }}"
          "-targetdir:${{ env.CODE_COVERAGE_REPORT_FOLDER_PATH }}"
          -reporttypes:Html

      - name: Upload Coverage Report to Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage-report
          path: ${{ env.CODE_COVERAGE_REPORT_FOLDER_PATH }}
          retention-days: 3